### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by IC1101Virgo** [IC1101Virgo/Care-To-Share#13]
The current site is too simple. An added option of dark mode can make the site more user-friendly.

**Comment by wojciechwachowiak** [comment]
can you assign this to me?

**Comment by IC1101Virgo** [comment]
@wojciechwachowiak Go ahead 🎊 Please feel free to ask any kind of doubts or problems 😄

**Comment by Harika-BV** [comment]
@IC1101Virgo Hey, I have added the dark mode/ light mode. Please check my PR

**Comment by IC1101Virgo** [comment]
@Harika-BV Just saw your changes. I am going to consider this time but this is not how issues work. The correct method is to first comment on the issue then wait for the issue to be assigned and then work on it. Please remember it next time.
Thank you.
