### ISSUE TITLE
Enhance the Toggle button

### ISSUE THREAD

**Issue by IC1101Virgo** [IC1101Virgo/Care-To-Share#27]
The current toggle button does not specify "DARK MODE". Some people would get confused using it. Change the toggle button entirely also do specify in the design that the button is Dark Button.

**Comment by mkamranhamid** [comment]
Hey, I would like to work on it. I was thinking if you have anything in mind or should I add an animation to it ?

**Comment by IC1101Virgo** [comment]
@mkamranhamid Please go ahead! And yes you can use your own ideas just make sure that people who visit the site easily get to know there is Dark Mode current toggle button is a little confusing 😅 
Please tell me if there is any doubt or problem 😃

**Comment by mkamranhamid** [comment]
I can see some issues in here like
- elements outside `<body>` tag
- `<html>` tag is not closed
- usage of obsolete tags like `< center>`
- code is not formatted

**Comment by mkamranhamid** [comment]
I've created a [PR](https://github.com/IC1101Virgo/Care-To-Share/pull/28). Please have a look at it
